#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: MIT
START=99
STOP=10
USE_PROCD=1

start_service() {
	[ "$(uci -q get outbound-monitor.main.enabled)" = "0" ] && return 0
	procd_open_instance
	procd_set_param command /usr/bin/outbound-monitor daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger outbound-monitor
}
